(() => {
  function $(id){return document.getElementById(id)}
  const root=$('relationshipsGrid'), allianceRoot=$('allianceSetup');
  if(!root || !allianceRoot) return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const api=()=>window.BB19SocialAPI;
  const state=()=>api()?.getState();
  const name=h=>String(h?.displayName||h?.firstName||h?.lastName||h?.id||'Houseguest');
  const relKeys=[['friendship','Friendship'],['trust','Trust'],['loyalty','Loyalty'],['rivalry','Rivalry'],['respect','Respect'],['attraction','Attraction']];
  const presets={Neutral:['Unspecified',50,50,50,0,50,0],CloseFriends:['Close Friends',82,76,78,5,82,5],StrongAllies:['Allies',68,82,88,5,76,0],BestFriends:['Best Friends',94,90,94,2,88,8],Showmance:['Showmance',88,76,82,4,78,92],Bromance:['Bromance',88,82,86,4,84,4],Rivalry:['Rivalry',18,12,8,92,36,0],Frenemies:['Frenemies',58,34,28,62,58,8],SecretPair:['Secret Pair',78,86,90,3,74,10]};
  let relA,relB;
  function ensure(){const s=state(); if(!s) return null; relA=relA||s.houseguests[0]?.id; relB=relB||s.houseguests.find(h=>h.id!==relA)?.id; if(!s.houseguests.some(h=>h.id===relA))relA=s.houseguests[0]?.id; if(!s.houseguests.some(h=>h.id===relB)||relA===relB)relB=s.houseguests.find(h=>h.id!==relA)?.id; return s;}
  function getRel(s,a,b){api().normalize(); return s.relationships[a][b]}
  function renderRelationships(){const s=ensure(); if(!s||s.houseguests.length<2)return; const r=getRel(s,relA,relB); const opts=s.houseguests.map(h=>`<option value="${esc(h.id)}">${esc(name(h))}</option>`).join(''); root.innerHTML=`<div class="social-v11"><div class="social-title"><div><span class="eyebrow">RELATIONSHIP BUILDER</span><h3>Set the relationship between two Houseguests</h3><p>Pick two people, choose a quick preset, or fine-tune all six relationship traits.</p></div></div><div class="social-pair"><label>Houseguest A<select id="v11RelA">${opts}</select></label><label>Houseguest B<select id="v11RelB">${opts}</select></label></div><div class="social-presets"><strong>Quick presets</strong><div>${Object.keys(presets).map(k=>`<button type="button" data-preset="${k}">${k.replace(/([A-Z])/g,' $1').trim()}</button>`).join('')}</div></div><div class="social-details"><label>Relationship Type<select id="v11RelType">${['Unspecified','Showmance','Bromance','Best Friends','Close Friends','Allies','Rivalry','Mentor / Mentee','Family','Frenemies','Secret Pair','Other'].map(t=>`<option ${r.type===t?'selected':''}>${esc(t)}</option>`).join('')}</select></label><label class="v11-check"><input id="v11Both" type="checkbox" checked> Apply to both directions</label><div class="v11-sliders">${relKeys.map(([k,l])=>`<label><span>${l}<b id="v11Val_${k}">${Number(r[k]??0)}</b></span><input id="v11_${k}" type="range" min="0" max="100" value="${Number(r[k]??0)}"></label>`).join('')}</div><label>Notes<textarea id="v11Notes" rows="3">${esc(r.notes||'')}</textarea></label></div><button type="button" class="primary" id="v11SaveRel">SAVE RELATIONSHIP</button><span id="v11RelStatus" class="muted-note"></span></div>`; $('#v11RelA').value=relA;$('#v11RelB').value=relB; }
  function readData(){const d={type:$('#v11RelType').value,notes:$('#v11Notes').value}; relKeys.forEach(([k])=>d[k]=Number($('#v11_'+k).value)); return d}
  root.addEventListener('change',e=>{if(e.target.id==='v11RelA'||e.target.id==='v11RelB'){if(e.target.id==='v11RelA')relA=e.target.value;else relB=e.target.value;if(relA===relB){const s=state();relB=s.houseguests.find(h=>h.id!==relA)?.id}renderRelationships()}});
  root.addEventListener('input',e=>{const m=e.target.id?.match(/^v11_(friendship|trust|loyalty|rivalry|respect|attraction)$/);if(m)$('#v11Val_'+m[1]).textContent=e.target.value});
  root.addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(b){const p=presets[b.dataset.preset],d={type:p[0],friendship:p[1],trust:p[2],loyalty:p[3],rivalry:p[4],respect:p[5],attraction:p[6],notes:$('#v11Notes').value};api().setRelationship(relA,relB,d,$('#v11Both').checked);return}if(e.target.id==='v11SaveRel'){api().setRelationship(relA,relB,readData(),$('#v11Both').checked);const st=$('#v11RelStatus');if(st)st.textContent='Saved. The relationship is now part of this season.';}});
  function renderAlliances(){const s=api().normalize(); const members=s.houseguests.map(h=>`<label class="v11-member"><input type="checkbox" value="${esc(h.id)}"><span>${esc(name(h))}</span></label>`).join(''); const cards=(s.alliances||[]).filter(a=>a.custom).map(a=>`<div class="v11-alliance-card"><div><strong>${esc(a.name)}</strong><span>${esc(a.type||'Custom')} · Strength ${Number(a.strength??70)}/100 · ${esc(a.secrecy||'Public')}</span></div><div>${a.memberIds.map(id=>esc(name(s.houseguests.find(h=>h.id===id)))).join(', ')}</div><button type="button" data-remove-alliance="${esc(a.id)}">Remove</button></div>`).join(''); allianceRoot.innerHTML=`<div class="social-v11"><div class="social-title"><div><span class="eyebrow">ALLIANCE BUILDER</span><h3>Create as many overlapping alliances as you want</h3><p>Name the alliance, choose its type and select the members. Changes save immediately.</p></div></div><div class="v11-alliance-fields"><label>Alliance Name<input id="v11AllianceName" placeholder="e.g. The Level 6"></label><label>Alliance Type<select id="v11AllianceType">${['Majority Alliance','Core Alliance','Final Two','Final Three','Girls\' Alliance','Guys\' Alliance','Secret Alliance','Side Alliance','Team','Custom'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Goal<select id="v11AllianceGoal">${['Game control','Keep the core safe','Target outsiders','Protect a specific player','Make jury together','Final 2 / Final 3','Short-term voting bloc','Other'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Strength <b id="v11AllianceStrengthValue">70</b><input id="v11AllianceStrength" type="range" min="0" max="100" value="70"></label><label class="v11-check"><input id="v11AllianceSecret" type="checkbox"> Secret alliance</label></div><strong>Select members (2 or more)</strong><div class="v11-members">${members}</div><button type="button" class="primary" id="v11CreateAlliance">CREATE ALLIANCE</button><div class="v11-alliance-list">${cards||'<p class="muted-note">No custom alliances created yet.</p>'}</div></div>`; $('#v11AllianceStrength').addEventListener('input',e=>$('#v11AllianceStrengthValue').textContent=e.target.value); }
  allianceRoot.addEventListener('click',e=>{const rm=e.target.closest('[data-remove-alliance]');if(rm){api().removeAlliance(rm.dataset.removeAlliance);renderAlliances();return}if(e.target.id==='v11CreateAlliance'){const ids=[...allianceRoot.querySelectorAll('.v11-member input:checked')].map(x=>x.value);try{api().addAlliance({name:$('#v11AllianceName').value,type:$('#v11AllianceType').value,goal:$('#v11AllianceGoal').value,strength:$('#v11AllianceStrength').value,secrecy:$('#v11AllianceSecret').checked?'Secret':'Public',memberIds:ids});renderAlliances()}catch(err){alert(err.message)}}});
  function boot(){if(!api())return setTimeout(boot,50);api().normalize();renderRelationships();renderAlliances();}
  boot();
})();
